/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 9df67bfd07910d28e905013b8c7c1723)
interface __BaseEnv_CloudflareEnv {
  NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
  ASSETS: Fetcher;
  NEXT_PUBLIC_API_BASE: "https://api.xcp.io";
  API_WORKER: Fetcher /* xcp-api */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./.open-next/worker");
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
