-- Curated data table: the human-maintained allow/deny/label lists that the signal passes and read
-- handlers consume. Moved out of hard-coded arrays (src/indexer/curated.ts + the NAMES map in
-- read/exchanges.ts) so ops can edit them via /admin/curated without a redeploy. Seed below reproduces
-- today's exact hard-coded outputs. CLAUDE.md rule 8: schema (and its seed) lives in migrations.
--
-- kinds:
--   lowq          key=asset   curated low-quality (wash/scam/bridge) assets → asset_signals.low_quality
--   burn          key=addr    verified burn addresses → address_signals.is_burn
--   exchange      key=addr    curated CEX/consolidation wallets → address_signals.is_exchange (note=provenance)
--   exchange_name key=addr    operator label for an exchange wallet (value=label) → GET /v2/exchanges
--   grail         key=asset   known-iconic assets → tags(source='curated', tag='grail')

CREATE TABLE IF NOT EXISTS curated (
  kind  TEXT NOT NULL,
  key   TEXT NOT NULL,
  value TEXT,
  note  TEXT,
  PRIMARY KEY (kind, key)
);

INSERT OR IGNORE INTO curated (kind, key, value, note) VALUES
('lowq','A11984891106868617664',NULL,NULL),
('lowq','A13401453567681343017',NULL,NULL),
('lowq','A14074648224959053374',NULL,NULL),
('lowq','A16633791645021321509',NULL,NULL),
('lowq','A2384426809477115589',NULL,NULL),
('lowq','A2848268701430318990',NULL,NULL),
('lowq','A4391853287542981791',NULL,NULL),
('lowq','A5557021997076742535',NULL,NULL),
('lowq','A6545283291136814819',NULL,NULL),
('lowq','A7771332604329827915',NULL,NULL),
('lowq','A8857415869833437486',NULL,NULL),
('lowq','CRYPTONAIRA',NULL,NULL),
('lowq','DIAMONDBOND',NULL,NULL),
('lowq','DIKKE',NULL,NULL),
('lowq','ERDE',NULL,NULL),
('lowq','GPSHARES',NULL,NULL),
('lowq','GUANII',NULL,NULL),
('lowq','HANJ',NULL,NULL),
('lowq','HOMMALICOIN',NULL,NULL),
('lowq','KVELL',NULL,NULL),
('lowq','LUUSH',NULL,NULL),
('lowq','MACROSS',NULL,NULL),
('lowq','METISS',NULL,NULL),
('lowq','MUUI',NULL,NULL),
('lowq','NARUCHAN',NULL,NULL),
('lowq','NVST',NULL,NULL),
('lowq','OGPASS',NULL,NULL),
('lowq','ORDIPEPE',NULL,NULL),
('lowq','OXBT',NULL,NULL),
('lowq','PANDAGOLD',NULL,NULL),
('lowq','PERFECTCERTS',NULL,NULL),
('lowq','PIENA',NULL,NULL),
('lowq','PROTEIOS',NULL,NULL),
('lowq','RCANA',NULL,NULL),
('lowq','RESORTLIFE',NULL,NULL),
('lowq','RIAM',NULL,NULL),
('lowq','TETLAS',NULL,NULL),
('lowq','TROPTIONS',NULL,NULL),
('lowq','VACUS',NULL,NULL),
('lowq','WOOOOK',NULL,NULL),
('lowq','COUNTEREVENT',NULL,NULL),
('lowq','RAIZER',NULL,NULL),
('lowq','FUHCOIN',NULL,NULL),
('lowq','TAOCOIN',NULL,NULL),
('lowq','NAGEZENI',NULL,NULL),
('lowq','XTROPTIONS',NULL,NULL),
('lowq','TROPTIONSPAY',NULL,NULL),
('lowq','TROPTIONSBC',NULL,NULL),
('lowq','A13836077288900301480',NULL,NULL),
('lowq','A4219293356469046725',NULL,NULL),
('lowq','A921933274660182119',NULL,NULL),
('burn','11ParticipantsXXXXXXXXXXXXXUGmPx6',NULL,NULL),
('burn','123AnditsGone111111111111111Ymiao1',NULL,NULL),
('burn','191mMadYoureMadxxxxxxxxxxxxxvwA4Up',NULL,NULL),
('burn','1AMpauLXXXXXXXXXXXXXXXXXXXWzywCd6j',NULL,NULL),
('burn','1AgeofChainsSeries1Burnxxxy1xR3Ao',NULL,NULL),
('burn','1AsseticBbXXXXXXXXXXXXXXXXXXbeMmNH',NULL,NULL),
('burn','1AsseticJLJLJLXXXXXXXXXXXXXXU87kKM',NULL,NULL),
('burn','1AsseticKanaddahXXXXXXXXXXXXRntPiE',NULL,NULL),
('burn','1AsseticXXXXXXXXXXXXXXXXXXXXY69xbC',NULL,NULL),
('burn','1AsseticooakosiMoXXXXXXXXXXXVWtCYm',NULL,NULL),
('burn','1AsswhoisitXXXXXXXXXXXXXXXXXY2F4pu',NULL,NULL),
('burn','1BURNFoWXXXXXXXXXXXXXXXXXXXY5LRms',NULL,NULL),
('burn','1BURNSogXXXXXXXXXXXXXXXXXXXXW3ny2Y',NULL,NULL),
('burn','1BURNTSH1RTxxxxxxxxxxxxxxxxuckhAY',NULL,NULL),
('burn','1BURNXXXXXXXXXXXXXXXXXXXXXXXTVanmh',NULL,NULL),
('burn','1BURNmentorsxxxxxxxxxxxxxxxwUtLJh',NULL,NULL),
('burn','1BitSupraBurnProofXXXXXXXXXXUqAPsu',NULL,NULL),
('burn','1BitcoinEaterAddressDontSend8MUo1T',NULL,NULL),
('burn','1BitcoinEaterAddressDontSendf59kuE',NULL,NULL),
('burn','1BitcornCropsMuseumAddressy149ZDr',NULL,NULL),
('burn','1BoJxKoKUSAixKAiToRixxxxxxwz1Pa5w',NULL,NULL),
('burn','1BurnDaNK476q5h7vtf3BTdqKpKu65SKbe',NULL,NULL),
('burn','1BurnFakePepexxxxxxxxxxxxxxzo7tqD',NULL,NULL),
('burn','1BurnPenisiumGrowPenisiumxxwGJvsx',NULL,NULL),
('burn','1BurnPepexxxxxxxxxxxxxxxxxxxAK33R',NULL,NULL),
('burn','1BurnRustxxxxxxxxxxxxxxxxxxzhjnHj',NULL,NULL),
('burn','1BurnSockxxxxxxxxxxxxxxxxxxwLPxbM',NULL,NULL),
('burn','1BurnXXXXXXXXXXXXXXXXXXXXXXXXekdRL',NULL,NULL),
('burn','1Burned4ReissuanceSwapChainzRe7Xq',NULL,NULL),
('burn','1Burningxcpassetsxxxxxxxxxy3ee2wH',NULL,NULL),
('burn','1BurnxxxxxxxxxxxxxxxxxxxxxxxLsYYK',NULL,NULL),
('burn','1ByeschoepepeXXXXXXXXXXXXXXXcpHGww',NULL,NULL),
('burn','1CKGAMEBURNiTALLxxxxxxxxxxxxeLDrH',NULL,NULL),
('burn','1CNTSMKxxxxxxxxxxxxxxxxxxxxtSetKh',NULL,NULL),
('burn','1CRiNGEXXXXXXXXXXXXXXXXXXXXXWTvJJP',NULL,NULL),
('burn','1ChancecoinXXXXXXXXXXXXXXXXXZELUFD',NULL,NULL),
('burn','1CornHawksxxxxxxxxxxxxxxxxxym3Kin',NULL,NULL),
('burn','1CoinandpeaceburnaddressXXWwTTyPw',NULL,NULL),
('burn','1CounterpartyXXXXXXXXXXXXXXXUWLpVr',NULL,NULL),
('burn','1CryptoLifeDotNetBurnAddrXXXSdVx52',NULL,NULL),
('burn','1DARKCLAMXF1NALXBURNXXXXXXXXVcPtLv',NULL,NULL),
('burn','1DARKCLAMxBURNXXXXXXXXXXXXXXVvbpkg',NULL,NULL),
('burn','1DARKCLAMxDooGXXXXXXXXXXXXXXZPbYip',NULL,NULL),
('burn','1DJasanyanxxxxxxxxxxxxxxxxy1uERgj',NULL,NULL),
('burn','1FauxSoGsBURNxxxxxxxxxxxxxxzme7me',NULL,NULL),
('burn','1FractaLPepeTESTxxxxxxxxxxxuRn48D',NULL,NULL),
('burn','1GEMZBURNXXXXXXXXXXXXXXXXXXXVUKFt4',NULL,NULL),
('burn','1GenesisxxxxxxxxxxxxxxxxxxxuRkNpc',NULL,NULL),
('burn','1JGBcoinKokusaiKaitorixxxxxD2iTTp',NULL,NULL),
('burn','1JesseFuckedUpxxxxxxxxxxxxxxvk6ma',NULL,NULL),
('burn','1KevineroBurnxxxxxxxxxxxxxxzbrvmF',NULL,NULL),
('burn','1LTBBURNxxxxxxxxxxxxxxxxxxxxQiaRZ',NULL,NULL),
('burn','1MafiaWarsGameBurnAddressxy1WbzYg',NULL,NULL),
('burn','1MouLaBurnXXXXXXXXXXXXXXXXXWcixDo',NULL,NULL),
('burn','1MouLaBurnxxxxxxxxxxxxxxxxxxEXzj4',NULL,NULL),
('burn','1NPCReprogrammingxxxxxxxxxxtqVgmX',NULL,NULL),
('burn','1NightStaLksxxxxxxxxxxxxxxxxcZVzv',NULL,NULL),
('burn','1PLiPBuRNxxxxxxxxxxxxxxxxxxzEyg27',NULL,NULL),
('burn','1PhockheadsBurnAddressxxxxxtEmomy',NULL,NULL),
('burn','1RaribLePEPEPARTYxxxxxxxxxy1a4EHk',NULL,NULL),
('burn','1Satanxxxxxxxxxxxxxxxxxxxxxw4d9KE',NULL,NULL),
('burn','1SatoshiRoundtab1exxxxxxxxxtJidRK',NULL,NULL),
('burn','1SwarmxxxxxxxxxxxxxxxxxxxxxwwCyWx',NULL,NULL),
('burn','1TestxxxxxxxxxxxxxxxxxxxxxxzoXNkw',NULL,NULL),
('burn','1Trigburnxxxxxxxxxxxxxxxxxxw5X1QR',NULL,NULL),
('burn','1WatchYourBTCBurnxxxxxxxxxxunS7dA',NULL,NULL),
('burn','1WhatissynereoXXXXXXXXXXXXX4p2rSe',NULL,NULL),
('burn','1bitfinexxxxxxxxxxxxxxxxxxxzjVHxU',NULL,NULL),
('burn','1burn11111111111111111111113yQZiQ',NULL,NULL),
('burn','1craigxxxxxxxxxxxxxxxxxxxxxsveXGX',NULL,NULL),
('burn','1cryptohivexxxxxxxxxxxxxxxxuZjrB6',NULL,NULL),
('burn','1editxxxxxxxxxxxxxxxxxxxxxxwKh9EC',NULL,NULL),
('burn','1finaxxxxxxxxxxxxxxxxxxxxxxtpcuxf',NULL,NULL),
('burn','1haiLLordkekxxxxxxxxxxxxxxxtn8WwC',NULL,NULL),
('burn','1hardforkxxxxxxxxxxxxxxxxxxu9iBLr',NULL,NULL),
('burn','1hyugaxxxxxxxxxxxxxxxxxxxxxtkbLXZ',NULL,NULL),
('burn','1infamousGraveyardRiPzzzzzzyQKytV',NULL,NULL),
('burn','1kanoxxxxxxxxxxxxxxxxxxxxxxztz7Sb',NULL,NULL),
('burn','1kinoshitaxxxxxxxxxxxxxxxxy27FE4R',NULL,NULL),
('burn','1kojixxxxxxxxxxxxxxxxxxxxxy46RA3r',NULL,NULL),
('burn','1mikehearnxxxxxxxxxxxxxxxxxzxJYCq',NULL,NULL),
('burn','1oishixxxxxxxxxxxxxxxxxxxxxxFftCZ',NULL,NULL),
('burn','1r3xxxxxxxxxxxxxxxxxxxxxxxy44N3ru',NULL,NULL),
('burn','1scamSCAMscamXXXXXXXXXXXXXXXYCXxk',NULL,NULL),
('burn','1segwitxxxxxxxxxxxxxxxxxxxxxwqcT1',NULL,NULL),
('burn','1shadi1aythug1ifexxxxxxxxxxuCqHNS',NULL,NULL),
('burn','1shitcoinxxxxxxxxxxxxxxxxxxwY1LYu',NULL,NULL),
('burn','1stLiquidPepexxxxxxxxxxxxxxumd9b8',NULL,NULL),
('burn','1sugiixxxxxxxxxxxxxxxxxxxxxy8KU3n',NULL,NULL),
('burn','1thedaoxxxxxxxxxxxxxxxxxxxy3gNefa',NULL,NULL),
('burn','1tokeneconomyxxxxxxxxxxxxxxshrDv5',NULL,NULL),
('burn','1wadaxxxxxxxxxxxxxxxxxxxxxy1c6a95',NULL,NULL),
('burn','1zakiyamaxxxxxxxxxxxxxxxxxxw7ybLT',NULL,NULL),
('burn','1BitcornSubmissionFeeAddressgL5Xg',NULL,NULL),
('burn','1MonapartyMMMMMMMMMMMMMMMMMQ3QJNm',NULL,NULL),
('burn','1PenPenWaLksToTheMountainnno8UBXN',NULL,NULL),
('burn','1DownTheDrainHahaYouFucksxy1LjwNf',NULL,NULL),
('burn','1111111111111111111114oLvT2',NULL,NULL),
('burn','1SaLvationGodsMarveLousGracaLgYQS',NULL,NULL),
('burn','1KekuSemauKKWhyphenSM3WpepezAEe4Y',NULL,NULL),
('burn','1JohnViLLARchiguireitorxxxxwhsz7P',NULL,NULL),
('burn','1GMoneyLovesHisConspiraciesXVpgPNR',NULL,NULL),
('exchange','1AeqgtHedfA2yVXH6GiKLS2JGkfWfgyTC6',NULL,'Bittrex (chat-confirmed)'),
('exchange','1XCPdWb6kk7PGfvbdRbRuNh51aPc4vqC7',NULL,'Poloniex (chat-confirmed)'),
('exchange','1Po1oXMCWobE6kxWr8rJEP1SRq71JSD3t4',NULL,'Poloniex (vanity ''Po1oX''; community-confirmed)'),
('exchange','1BCYpzZAmH3pX7EXU6s4gxtG1AoVMn2NfJ',NULL,'Poloniex (BCY vanity; community-confirmed)'),
('exchange','1PNkBxnz5ePW8FeK6CSs8V2fGHcN9B6HNk',NULL,'Zaif - community-confirmed'),
('exchange','1NFeBp9s5aQ1iZ26uWyiK2AYUXHxs7bFmB',NULL,'BTER (old) - community-confirmed (peak ~170k XCP)'),
('exchange','1GEMZsZZQ32YqX3nzBptQLJBAtn1XByRCZ',NULL,'Poloniex (GEMZ vanity; community-confirmed)'),
('exchange','19fNvdGbD3dP5zqAsQhDqGyENnR5bHvZB1',NULL,'DEX-Trade hot wallet (chat-confirmed)'),
('exchange','1LhEGAPUZnfNDbh7oFogdekUyTW8NBfW3g',NULL,'DEX-Trade wallet #2 (chat-confirmed)'),
('exchange','1SJCXrYsuWmZzmAhA9K4fYkKqgGyLim79',NULL,'Poloniex (SJCX vanity; community-confirmed)'),
('exchange','1FLDCfr9iG7n6bAdGsqBXmhaLgC4aSze72',NULL,'Poloniex (FLDC vanity; community-confirmed)'),
('exchange','1LTBCyh9dKhNNZFaByPXfrkeuAD7yr6A4b',NULL,'Poloniex (LTBC vanity; community-confirmed)'),
('exchange','1AhAExgxS6aVRdKdyEuC5M4v6dxdzdgTaq',NULL,'Zaif (chat-confirmed; vanity ''Exg'')'),
('exchange','15ctNNSfo84dW5Ki8fTkcqbFAyfGbBXwsC',NULL,'Poloniex cold storage (chat-confirmed)'),
('exchange','1Co1dcFX6u1wQ8cW8mnj1DEgW7xQMEaChD',NULL,'Poloniex cold storage (probable) — ''Co1d'' vanity; cold-wallet profile (19 senders, 20 assets, 2015-22)'),
('exchange','1N9XWkNp4zPykh8kajbwJXY5d5ZzkQXs3L',NULL,'Huobi deposit (chat-confirmed)'),
('exchange','1F2zjMv6dTwTW4r9fJ7zTonXp7Tfk23su3',NULL,'Zaif #1 - community-confirmed (131k XCP; was suspected whale-FP)'),
('exchange','3DZzgGNxsSK1XyUJcKHLM9PxLTEypPGo8W',NULL,'Zaif #2 - community-confirmed'),
('exchange','1ML2b9tY5V8S9qQw6jNUs5uxkm6nKayk6x',NULL,'Zaif cold - community-confirmed (emptied -> 1F2zjM)'),
('exchange','1E1QuzwVeLdnQdNq38gBsyH8ht39UdHPAh',NULL,'Zaif - community-confirmed'),
('exchange','1AqUTSTGB6coR5AYcwFFM6nXoULapXqtdL',NULL,'TUX - community-confirmed'),
('exchange','1CcWRPF4Eksnn49Rx2dZ3dgJW9kiX8VGE2',NULL,'TUX - WalletExplorer cluster match to 1AqUTST (round-trip 17.7%)'),
('exchange','12PrRwgmAgsVJy8G7uQryi78ugGurt7vaM',NULL,'BTER - community-confirmed'),
('exchange','1PH4KzJ7VpwPZR3VnP8anmcMTjJEGt73Gz',NULL,'Zaif/Tech Bureau issuer - community-confirmed'),
('exchange','14rR75DYPaKLSt6UHBakR2h3n8QadTEGxG',NULL,'Zaif/Tech Bureau issuer - community-confirmed'),
('grail','FDCARD',NULL,NULL),
('grail','SATOSHICARD',NULL,NULL),
('grail','RAREPEPE',NULL,NULL),
('grail','DARKPILLPEPE',NULL,NULL),
('grail','WINKELPEPE',NULL,NULL),
('grail','PEPEALASSAD',NULL,NULL),
('grail','TEST',NULL,NULL),
('grail','NINJASUIT',NULL,NULL),
('grail','PEPECASH',NULL,NULL),
('grail','FAKERARE',NULL,NULL),
('exchange_name','1AeqgtHedfA2yVXH6GiKLS2JGkfWfgyTC6','Bittrex',NULL),
('exchange_name','1XCPdWb6kk7PGfvbdRbRuNh51aPc4vqC7','Poloniex',NULL),
('exchange_name','1Po1oXMCWobE6kxWr8rJEP1SRq71JSD3t4','Poloniex',NULL),
('exchange_name','1BCYpzZAmH3pX7EXU6s4gxtG1AoVMn2NfJ','Poloniex',NULL),
('exchange_name','1GEMZsZZQ32YqX3nzBptQLJBAtn1XByRCZ','Poloniex',NULL),
('exchange_name','1SJCXrYsuWmZzmAhA9K4fYkKqgGyLim79','Poloniex',NULL),
('exchange_name','1FLDCfr9iG7n6bAdGsqBXmhaLgC4aSze72','Poloniex',NULL),
('exchange_name','1LTBCyh9dKhNNZFaByPXfrkeuAD7yr6A4b','Poloniex',NULL),
('exchange_name','15ctNNSfo84dW5Ki8fTkcqbFAyfGbBXwsC','Poloniex',NULL),
('exchange_name','1Co1dcFX6u1wQ8cW8mnj1DEgW7xQMEaChD','Poloniex',NULL),
('exchange_name','1PNkBxnz5ePW8FeK6CSs8V2fGHcN9B6HNk','Zaif',NULL),
('exchange_name','1AhAExgxS6aVRdKdyEuC5M4v6dxdzdgTaq','Zaif',NULL),
('exchange_name','1F2zjMv6dTwTW4r9fJ7zTonXp7Tfk23su3','Zaif',NULL),
('exchange_name','3DZzgGNxsSK1XyUJcKHLM9PxLTEypPGo8W','Zaif',NULL),
('exchange_name','1ML2b9tY5V8S9qQw6jNUs5uxkm6nKayk6x','Zaif',NULL),
('exchange_name','1E1QuzwVeLdnQdNq38gBsyH8ht39UdHPAh','Zaif',NULL),
('exchange_name','1PH4KzJ7VpwPZR3VnP8anmcMTjJEGt73Gz','Zaif/Tech Bureau',NULL),
('exchange_name','14rR75DYPaKLSt6UHBakR2h3n8QadTEGxG','Zaif/Tech Bureau',NULL),
('exchange_name','1N9XWkNp4zPykh8kajbwJXY5d5ZzkQXs3L','Huobi',NULL);
